### PR TITLE
Added backlight timeout 1sec

### PR DESCRIPTION
**Pull request by CrisBalGreece**

### CODE REVIEW

**Review by poad42 — CHANGES_REQUESTED** [review]
the commit : https://github.com/DerpLab/platform_packages_apps_DerpQuest/pull/54/commits/225db9f4874416f2ca6f6223161c352b41adbe23 and https://github.com/DerpLab/platform_packages_apps_DerpQuest/pull/54/commits/5cd638f0d550d39db9f4e76cf89ad40dc47e0411 can be squashed plus fix alignments please.

**Comment by idoybh** [comment]
> the commit : [225db9f](https://github.com/DerpLab/platform_packages_apps_DerpQuest/commit/225db9f4874416f2ca6f6223161c352b41adbe23) and [5cd638f](https://github.com/DerpLab/platform_packages_apps_DerpQuest/commit/5cd638f0d550d39db9f4e76cf89ad40dc47e0411) can be squashed plus fix alignments please.

It's called tabbing :) And dw. I will make this a seekbar

**Comment by idoybh** [comment]
keeping open to link the commit here when done

**Comment by idoybh** [comment]
https://github.com/DerpLab/platform_packages_apps_DerpQuest/commit/4cd5c3427b21279677cae2a47d31810f6eec9ece

There ya go fellas. Thanks for the idea @CrisBalGreece and thanks for the comments and attention as always @poad42. Closing this now.

**Pull request closed without merging**
